const CLOUDINARY_APP_PATH = "wap";
const CLOUDINARY_DOGS_PATH = `${CLOUDINARY_APP_PATH}/dogs`;
const CLOUDINARY_USERS_PATH = `${CLOUDINARY_APP_PATH}/users`;
const CLOUDINARY_MEN_PATH = `${CLOUDINARY_USERS_PATH}/men`;
const CLOUDINARY_WOMEN_PATH = `${CLOUDINARY_USERS_PATH}/women`;

module.exports = {
  CLOUDINARY_APP_PATH,
  CLOUDINARY_DOGS_PATH,
  CLOUDINARY_MEN_PATH,
  CLOUDINARY_WOMEN_PATH,
};
