const dog_male_name = [
  "Max",
  "Charlie",
  "Rocky",
  "Duke",
  "Bailey",
  "Buddy",
  "Jack",
  "Cooper",
  "Bear",
  "Toby",
  "Harley",
  "Oliver",
  "Oscar",
  "Bentley",
  "Teddy",
  "Finn",
  "Riley",
  "Simba",
  "Scout",
  "Milo",
  "Diesel",
  "Louie",
  "Jasper",
  "Rex",
  "Hunter",
  "Murphy",
  "Ace",
  "Gus",
  "Jake",
  "Zeus",
  "Boomer",
  "Buster",
  "Shadow",
  "Bruno",
  "Tucker",
  "Chester",
  "King",
  "Samson",
  "Bruce",
  "Ranger",
  "Chip",
  "Thor",
  "Moose",
  "Tank",
  "Champ",
  "Leo",
];

const dog_female_name = [
  "Bella",
  "Luna",
  "Molly",
  "Sadie",
  "Lucy",
  "Maggie",
  "Chloe",
  "Sophie",
  "Zoey",
  "Daisy",
  "Stella",
  "Roxy",
  "Ruby",
  "Penny",
  "Lily",
  "Lola",
  "Pepper",
  "Coco",
  "Nala",
  "Hazel",
  "Ginger",
  "Lexi",
  "Zoe",
  "Ellie",
  "Rosie",
  "Emma",
  "Piper",
  "Layla",
  "Willow",
  "Nova",
  "Mia",
  "Annie",
  "Callie",
  "Belle",
  "Athena",
  "Dakota",
  "Cleo",
  "Sasha",
  "Abby",
  "Frankie",
  "Izzy",
  "Phoebe",
  "Harper",
  "Delilah",
  "Pearl",
  "Minnie",
  "Olive",
  "Honey",
  "Sandy",
  "Trixie",
];

const menFirstname = [
  "Adam",
  "Adrien",
  "Alban",
  "Alexandre",
  "Alfred",
  "Amine",
  "Antoine",
  "Armand",
  "Arthur",
  "Augustin",
  "Aurélien",
  "Axel",
  "Bastien",
  "Benjamin",
  "Benoît",
  "Bertrand",
  "Bruno",
  "Cédric",
  "Charles",
  "Christophe",
  "Clément",
  "Corentin",
  "Damien",
  "David",
  "Denis",
  "Didier",
  "Dorian",
  "Edouard",
  "Emmanuel",
  "Enzo",
  "Étienne",
  "Fabien",
  "Fabrice",
  "Florian",
  "Francis",
  "François",
  "Gabriel",
  "Gaël",
  "Geoffrey",
  "Gilles",
  "Grégoire",
  "Guillaume",
  "Hugo",
  "Ian",
  "Ibrahim",
  "Jérémy",
  "Jean",
  "Jonathan",
  "Jordan",
  "Joseph",
  "Jules",
  "Julien",
  "Kévin",
  "Léo",
  "Léon",
  "Loïc",
  "Louis",
  "Lucas",
  "Lucien",
  "Ludovic",
  "Mahdi",
  "Marc",
  "Marcel",
  "Martin",
  "Matéo",
  "Mathieu",
  "Matthias",
  "Maxime",
  "Michaël",
  "Michel",
  "Nathan",
  "Nicolas",
  "Noah",
  "Olivier",
  "Oscar",
  "Pascal",
  "Paul",
  "Philippe",
  "Pierre",
  "Quentin",
  "Raphaël",
  "Rémi",
  "Renaud",
  "Robin",
  "Romain",
  "Sébastien",
  "Simon",
  "Stanislas",
  "Stéphane",
  "Sylvain",
  "Théo",
  "Thomas",
  "Tristan",
  "Valentin",
  "Victor",
  "Vincent",
  "William",
  "Xavier",
  "Yann",
  "Yves",
];

const womenFirstname = [
  "Emma",
  "Louise",
  "Chloé",
  "Sofia",
  "Léa",
  "Manon",
  "Camille",
  "Lina",
  "Zoé",
  "Juliette",
  "Alice",
  "Lola",
  "Anna",
  "Mia",
  "Élise",
  "Inès",
  "Sarah",
  "Clara",
  "Marie",
  "Lucie",
  "Nina",
  "Agathe",
  "Charlotte",
  "Eva",
  "Ambre",
  "Jade",
  "Margaux",
  "Maëlle",
  "Célia",
  "Pauline",
  "Gabrielle",
  "Océane",
  "Romane",
  "Éva",
  "Alix",
  "Amandine",
  "Léna",
  "Elodie",
  "Justine",
  "Olivia",
  "Amélie",
  "Adèle",
  "Laura",
  "Elsa",
  "Maïa",
  "Cécile",
  "Aurélie",
  "Victoria",
  "Suzanne",
  "Hélène",
  "Émilie",
  "Sophie",
  "Blandine",
  "Perrine",
  "Margot",
  "Flora",
  "Violette",
  "Noémie",
  "Clémence",
  "Mathilde",
  "Yasmine",
  "Amara",
  "Nora",
  "Capucine",
  "Éloïse",
  "Maëlys",
  "Caroline",
  "Mélanie",
  "Axelle",
  "Alison",
  "Gaëlle",
  "Iris",
  "Lily",
  "Lucille",
  "Morgane",
  "Aurore",
  "Emilie",
  "Fanny",
  "Coralie",
  "Anaïs",
  "Marion",
  "Sabrina",
  "Colette",
  "Evelyne",
  "Madeleine",
  "Rosalie",
  "Laurine",
  "Isabelle",
  "Geneviève",
  "Claire",
  "Elina",
  "Véronique",
  "Eloïse",
  "Amalia",
  "Estelle",
  "Aline",
  "Clarisse",
  "Juliana",
  "Gabriela",
  "Tiffany",
];

const lastname = [
  "Martin",
  "Bernard",
  "Thomas",
  "Petit",
  "Robert",
  "Richard",
  "Durand",
  "Dubois",
  "Moreau",
  "Laurent",
  "Simon",
  "Michel",
  "Lefebvre",
  "Leroy",
  "Roux",
  "David",
  "Bertrand",
  "Morel",
  "Fournier",
  "Girard",
  "Bonnet",
  "Dupont",
  "Lambert",
  "Fontaine",
  "Rousseau",
  "Vincent",
  "Muller",
  "Lefevre",
  "Faure",
  "Andre",
  "Mercier",
  "Blanc",
  "Guerin",
  "Boyer",
  "Garnier",
  "Chevalier",
  "Francois",
  "Legrand",
  "Gauthier",
  "Garcia",
  "Perrin",
  "Robin",
  "Clement",
  "Morin",
  "Nicolas",
  "Henry",
  "Roussel",
  "Mathieu",
  "Gautier",
  "Masson",
  "Marchand",
  "Duval",
  "Denis",
  "Dumont",
  "Marie",
  "Lemoine",
  "Noel",
  "Meyer",
  "Dufour",
  "Meunier",
  "Brun",
  "Blanchard",
  "Giraud",
  "Joly",
  "Riviere",
  "Lucas",
  "Brunet",
  "Gaillard",
  "Barbier",
  "Arnaud",
  "Martinez",
  "Gerard",
  "Roche",
  "Renard",
  "Schmitt",
  "Roy",
  "Lemoine",
  "Perrier",
  "Colin",
  "Vidal",
  "Caron",
  "Picard",
  "Roger",
  "Fabre",
  "Aubert",
  "Lemoine",
  "Lemoigne",
  "Dupuis",
  "Paul",
  "Dumas",
  "Rolland",
  "Leclerc",
  "Guillaume",
  "Lecomte",
  "Lopez",
  "Jean",
  "Fernandez",
  "Baron",
  "Guyot",
  "Carpentier",
];

const restaurants_name = [
  "Le Gourmet Français",
  "Pasta Paradiso",
  "Sushi Zen",
  "Steakhouse Royale",
  "Pizza Bella",
  "Chez Monique",
  "L'Étoile Dorée",
  "Bistro Lumière",
  "Burger Haven",
  "Taj Mahal Curry House",
  "El Rancho Mexicano",
  "Seafood Delight",
  "Café de Paris",
  "The Green Bowl",
  "Barbecue Junction",
  "Fusion Kitchen",
  "La Casa Italiana",
  "Dragon Wok",
  "Vegan Vibes",
  "Chez Henri",
  "Le Petit Bistro",
  "The Rustic Oven",
  "Pho Noodle House",
  "Curry Express",
  "The Breakfast Spot",
  "Garden Fresh Café",
  "Bella Pasta",
  "Château de Saveurs",
  "Golden Dragon",
  "Soul Food Station",
  "Tropical Tastes",
  "The Sushi Bar",
  "The Urban Grill",
  "Crepes & Co.",
  "Spicy Corner",
  "La Table Ronde",
  "Pizza Supreme",
  "Ocean Breeze Diner",
  "BBQ King",
  "Boulangerie Délice",
  "Mama's Kitchen",
  "The Italian Bistro",
  "Royal Curry Palace",
  "The Pancake House",
  "La Trattoria",
  "Saffron Lounge",
  "Noodle Nirvana",
  "Burger Bliss",
  "Thai Spice",
  "Café Jardin",
  "The Artisan Pizzeria",
  "Tokyo Tempura",
  "Mediterranean Feast",
  "Savory Spoons",
  "Casa Mexicana",
  "Golden Fork",
  "The Daily Grind",
  "Le Bistro Vert",
  "The Classic Grill",
  "Taste of India",
  "Tapas y Sangria",
  "Bistro des Amis",
  "Chef's Table",
  "Pasta e Basta",
  "The Salad Bar",
  "Pho Paradise",
  "The Spice Trail",
  "Chez Marcel",
  "Ramen Retreat",
  "Caribbean Flavors",
  "La Bonne Crêpe",
  "The Steak Loft",
  "Dim Sum House",
  "Farm to Table",
  "Bistro Nouveau",
  "Pizzeria Napoli",
  "Savory Bites",
  "Le Coin Gourmand",
  "Fusion Delights",
  "The Urban Taco",
  "Chez Claudine",
  "Flavors of Morocco",
  "The Cozy Café",
  "Burger Shack",
  "The Fish Market",
  "La Petite Table",
  "The Waffle Spot",
  "Sushi & Sake",
  "The Curry Leaf",
  "The Sandwich Stop",
  "Bistro Bon Appétit",
  "The Breakfast Club",
  "Le Soleil",
  "Tandoori Treasure",
  "Street Food Fusion",
  "The Pasta Bowl",
  "Chez Pierre",
  "The Garden Grill",
  "Hibachi House",
  "La Brasserie"
];

const bars_name = [
  "The Tipsy Tavern",
  "Le Zinc",
  "Moonlight Bar",
  "The Velvet Lounge",
  "Whiskey & Co.",
  "The Golden Mug",
  "Café des Amis",
  "The Hidden Gem",
  "Bar 42",
  "The Drunken Sailor",
  "L'Apéro",
  "The Rusty Barrel",
  "Midnight Oasis",
  "The Rooftop Spot",
  "Cocktail Dreams",
  "La Taverne Dorée",
  "The Black Cat",
  "Bubbles & Booze",
  "La Cave à Vins",
  "Gin & Tonic Lounge",
  "The Secret Cellar",
  "The Last Call",
  "Bar Eclipse",
  "Le Comptoir",
  "The Electric Lemon",
  "Rum Haven",
  "The Ice Breaker",
  "Speakeasy 1920",
  "Le Mojito Club",
  "The Chill Spot",
  "Le Baroque",
  "The Salty Dog",
  "The Oak Barrel",
  "Bar Nocturne",
  "The Jazz Joint",
  "Skyline Bar",
  "La Nuit Blanche",
  "The Hoppy Place",
  "Bar Botanique",
  "The Crimson Fox",
  "Tap & Barrel",
  "The Sunset Sip",
  "La Bohème",
  "The Wanderlust Pub",
  "Bar Clandestin",
  "The Sapphire Lounge",
  "Le Cerf Noir",
  "The Liquor Loft",
  "Urban Vibes Bar",
  "The Gin Joint",
  "Bar Éphémère",
  "The Copper Coin",
  "Le Bistrot Bleu",
  "The Wild Goose",
  "Amber Ale House",
  "The Cozy Corner",
  "Le Verre à Pied",
  "The Crown & Anchor",
  "Bar Mirage",
  "The Scarlet Owl",
  "Les Bulles Dorées",
  "Whiskey Nights",
  "The Lighthouse Pub",
  "La Fée Verte",
  "The Firefly Bar",
  "L'Escale",
  "The Cheers Spot",
  "The Roaring Lion",
  "Le Canard Joyeux",
  "The Frosted Glass",
  "Bar Horizon",
  "The Pearl Lounge",
  "Citrus & Spice",
  "The Anchor's End",
  "Le Refuge",
  "The High Spirits",
  "Bar des Rêves",
  "The Midnight Mule",
  "Le Chêne Vert",
  "The Vintage Tap",
  "The Sapphire Fox",
  "Bar des Étoiles",
  "The Liquid Lab",
  "Le Sunset Bar",
  "The Drunken Parrot",
  "Bar à Mousse",
  "The Midnight Barrel",
  "Le Relais",
  "The Golden Stag",
  "Spirits & Co.",
  "Bar Alchimie",
  "The Cloud Nine",
  "La Cave Secrète",
  "The Mystic Pint",
  "Bar Renaissance",
  "The Rebel Alehouse",
  "Le Flambeau",
  "The Neon Cactus",
  "Bar Mirage",
  "The Honeycomb",
  "La Terrasse Noire"
];

const shops_name = [
  "Paws & Whiskers",
  "Le Toutou Chic",
  "Happy Tails Boutique",
  "The Barking Lot",
  "Canine Couture",
  "Pup Paradise",
  "La Patte Dorée",
  "Wagging Wonders",
  "Doggo's Den",
  "Furry Friends Supplies",
  "Collars & Co.",
  "The Dog House",
  "Bark Avenue",
  "Puppy Love Emporium",
  "Tail Waggers",
  "Chew Toys Galore",
  "Canine Kingdom",
  "Woof & Style",
  "The Leash Loft",
  "La Boutique Canine",
  "Pawfection Accessories",
  "Bone & Biscuit",
  "The Happy Hound",
  "Fetch & Co.",
  "Sniff & Treat",
  "Chien Élégant",
  "Pawsitively Perfect",
  "Fur Baby Supplies",
  "The Doggie Depot",
  "Bark Boutique",
  "Hound Haven",
  "Luxe Paws",
  "Pup's Playhouse",
  "Le Collier Charmant",
  "Tailored Tails",
  "The Pampered Pup",
  "Wag & Woof",
  "Paw Prints Paradise",
  "Ruff & Fluff",
  "The Bark Stop",
  "Doggie Dreams",
  "The Treat Trail",
  "Furry Tail Boutique",
  "Pup Essentials",
  "Chien Confort",
  "Pawsh Accessories",
  "The Wagging Tail",
  "Hound & Collar",
  "Cuddle Paws",
  "The Doggie Drawer",
  "Bark & Bone",
  "The Leash Lounge",
  "Fetch Boutique",
  "Woof Wonderland",
  "Pawfect Finds",
  "Bark & Sparkle",
  "Fur Seasons",
  "The Doggy Basket",
  "Paws and Treats",
  "Tail Treasures",
  "The Puppy Palace",
  "Canine Central",
  "Pawfect Style",
  "The Doggie Corner",
  "Treats & Tails",
  "Le Chien Heureux",
  "Pup Couture",
  "Woof & Co.",
  "The Wagging Boutique",
  "Hound Haven Supplies",
  "Bark & Co.",
  "Doggy Essentials",
  "La Patte Parfaite",
  "Pup N' Play",
  "The Collar Collective",
  "Bone Boutique",
  "Fetch & Treat",
  "Woof & Wag",
  "Puppy Charm",
  "The Doggo Den",
  "Furry Essentials",
  "Tail Trends",
  "Pup Plaza",
  "Bark Basics",
  "Sniff & Style",
  "Happy Howls",
  "Pawfect Comfort",
  "The Tail Trail",
  "Doggy Delights",
  "La Truffe Dorée",
  "Canine Bliss",
  "Pup Paradise Emporium",
  "Woof Wardrobe",
  "The Doggy Den",
  "Collars & Paws",
  "Le Monde du Chien",
  "The Tail Boutique",
  "Paw Prints Supplies",
  "Hound Treasures",
  "Bark 'n' Roll"
];

const parks_name = [
  "Parc des Cèdres",
  "Jardin des Tuiles",
  "Parc du Ruisseau",
  "Bois des Lucioles",
  "Parc de la Clairière",
  "Jardin du Soleil",
  "Parc des Alizés",
  "Bois Fleuri",
  "Parc du Belvédère",
  "Jardin des Roses",
  "Parc des Étangs",
  "Promenade des Érables",
  "Parc de l'Horizon",
  "Jardin des Étoiles",
  "Forêt des Merveilles",
  "Parc des Amandiers",
  "Bois Enchanté",
  "Parc de la Cascade",
  "Jardin du Rivage",
  "Parc des Hirondelles",
  "Forêt Dorée",
  "Parc des Mélèzes",
  "Jardin des Sables",
  "Parc du Vent Doux",
  "Bois des Pins",
  "Jardin des Lotus",
  "Parc des Échos",
  "Forêt des Souvenirs",
  "Parc de la Brise",
  "Jardin des Ombelles",
  "Parc des Rêveries",
  "Bois Tranquille",
  "Parc du Lac Bleu",
  "Jardin des Lilas",
  "Parc des Libellules",
  "Bois des Murmures",
  "Jardin des Fougères",
  "Parc des Monts",
  "Forêt des Échos",
  "Parc de la Source",
  "Jardin des Camélias",
  "Parc de la Lisière",
  "Bois des Charmes",
  "Parc de l'Arche",
  "Jardin des Glycines",
  "Parc des Mésanges",
  "Forêt des Secrets",
  "Parc du Clair de Lune",
  "Jardin des Papillons",
  "Parc des Myosotis",
  "Bois des Écureuils",
  "Parc des Pins Verts",
  "Jardin des Marguerites",
  "Parc des Collines",
  "Forêt de la Sérénité",
  "Parc de la Prairie",
  "Jardin des Tulipes",
  "Parc des Aurores",
  "Bois du Silence",
  "Parc du Grand Chêne",
  "Jardin des Jonquilles",
  "Parc des Cigales",
  "Forêt de l'Aube",
  "Parc des Violettes",
  "Jardin des Églantiers",
  "Parc du Petit Pont",
  "Bois des Légendes",
  "Parc du Sentier Perdu",
  "Jardin des Perles",
  "Parc de la Lune Rousse",
  "Forêt des Alouettes",
  "Parc de la Mare",
  "Jardin des Muguets",
  "Parc des Bruyères",
  "Bois des Sources",
  "Parc des Platanes",
  "Jardin des Ombres",
  "Parc des Châtaigniers",
  "Forêt des Cerfs",
  "Parc des Cimes",
  "Jardin des Eaux Vives",
  "Parc de la Vallée Verte",
  "Bois des Promesses",
  "Parc des Roches Blanches",
  "Jardin des Éclats",
  "Parc des Fauvettes",
  "Forêt de l’Éveil",
  "Parc de l'Étang Clair",
  "Jardin des Orchidées",
  "Parc du Chemin Vert",
  "Bois des Mimosas",
  "Parc des Coquelicots",
  "Jardin du Printemps",
  "Parc des Pins Blancs",
  "Forêt des Aventures",
  "Parc des Senteurs",
  "Jardin des Capucines",
  "Parc de l'Aube Dorée",
  "Bois des Flèches"
];


module.exports = {
  dog_male_name,
  dog_female_name,
  menFirstname,
  womenFirstname,
  lastname,
  restaurants_name,
  bars_name,
  shops_name,
  parks_name
  
};
